import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import * as firebase from 'firebase/app';
// import { AngularFireAuth } from '@angular/fire/auth';
// import { auth } from 'firebase/app';

@Injectable({
  providedIn: 'root'
})
export class ConfigService {

  constructor() { }


  // ===================================================
  // MODO ADMIN
  // ===================================================
  public is_admin : boolean = false;

  // ===================================================
  // DESTINO DOS UPLOADS de imagens base64
  // firestore ou firebase
  // o firebase causa alto trafego porque o banco de dados é carregado totalmente a cada inicialização,
  // o que faz com que todas as imagens no banco de dados sejam carregadas, mesmo sem ser acessadas diretamente,
  // portanto, NAO USAR o método "firebase" a não ser que por um bom motivo e com os devidos cuidados
  // ===================================================
  public destino_dos_uploads = 'firestore';


  // ===================================================
  // ATIVAR GERENCIAMENTO DE CLIENTES E SOCIOS
  // ===================================================
  public ATIVAR_CLIENTES : boolean = true;
  public ATIVAR_SOCIOS : boolean = false;

  // =====================================================
  // Configuração de navegação
  // =====================================================
  public selected_user : any;

  public footer_img : string;
  public footer_img_alt : string;

  // =====================================================
  // Autenticação
  // =====================================================
  public user: string = '';
  public auth_object : any = '';
  public usuario_logado : any = {};
  public usuarios : any = {};
  public usuario : string = '';
  // ===================================================



    // ===================================================
    // PrimeNG Calendar
    // ===================================================
    public dates: Date[] = [];
    public invalidDates: Array<Date> = [];
    public rangeDates: Date[];
    public minDate: Date;
    public maxDate: Date;
    public rangeDates_iniciododia_data_inicial : number = 0;
    public rangeDates_fimdodia_data_final : number = 0;
    public data_inicial : string;
    public data_final : string;


    public pt : any = {
        firstDayOfWeek: 0,
        dayNames: ["Domingo", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado"],
        dayNamesShort: ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sab"],
        dayNamesMin: ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sab"],
        monthNames: [ "Janeiro","Fevereiro","Março","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro" ],
        monthNamesShort: [ "Jan", "Fev", "Mar", "Abr", "Mai", "Jun","Jul", "Ago", "Set", "Out", "Nov", "Dez" ],
        today: 'Hoje',
        clear: 'Limpar',
        dateFormat: 'dd/mm/yy',
        weekHeader: 'Sem'
    };
    // dayNamesMin: ["Do","Sg","Te","Qa","Qi","Sx","Sa"],
    // dayNamesMin: ["D","S","T","Q","Q","S","S"],



  // ===================================================
  // DIVERSOS
  // ===================================================
  public SEGUNDOS_AGUARDANDO_RECEBER_PAGINA_HTTP = 1;

  public dias_pra_credito_do_cartao : number = 40;

  public DISPLAY : any = {
      Agenda : false,
      AlertaEdit : false,
      DetalheDosDentes : false,
      Editar : false,
      EquipeErroDialog : false,
      ErroDialog : false,
      ExcluirDialog : false,
      Home : true,
      Lista : false,
      MarcarDente : false,
      PopupWhatsapp : false,
      Promocoes : false,
      Registro : false,
      Revisoes : false,
      StartPage : false,
      Whatsapp : false,
      Config : false,
      EditAtendimentos : false,
      EditPerfil : false,
      EditLancamentos : false,
  };


  public QUANTOS_POR_PAGINA_default = 5;

  public QUANTOS_POR_PAGINA : any = {
      ANIVERSARIOS : 5,
      ATENDIMENTOS : 5,
      BANCOS : 5,
      CAIXA : 5,
      CENTROS_DE_CUSTOS : 10,
      CENTROS_DE_CUSTOS_LISTA : 10,
      CONCILIACAO : 5,
      CONTAS : 5,
      CONFIG_FINANCEIRO : 5,
      DENTAIS : 5,
      DESPESAS : 10,
      FORNECEDORES : 5,
      EQUIPE : 5,
      FABRICANTES : 5,
      FINANCEIRO : 10,
      GESTAO : 5,
      HISTORICOS : 5,
      IMPRESSOS : 5,
      INDICADOR : 5,
      MOVIMENTACAO : 5,
      SOCIOS : 5,
      CLIENTES : 5,
      ESTOQUE : 5,
      PAGAMENTOS : 5,
      LANCAMENTOS_RECEITA : 5,
      LANCAMENTOS_DESPESA : 5,
      ORCAMENTOS : 5,
      COMUNICADOS : 5,
      RECEITAS : 10,
      REL_CENTROS_DE_CUSTOS : 5,
      REL_CENTROS_DE_CUSTOS_TOTALIZADOS : 5,
      REL_DINHEIRO : 31,
      REL_CHEQUES_PRE : 31,
      REL_CHEQUES_A_VISTA : 31,
      DISPONIBILIDADE : 31,
      REL_EXTRATO_DE_CONTAS : 5,
      REL_RECEITAS_E_DESPESAS : 5,
      RELATORIOS : 10,
      RESULTADOS : 31,
      REVISOES : 5,
      TRANSFERENCIAS : 10,
      USUARIOS : 5,
      PRODUCAO_PROFISSIONAL : 5,
      ULTIMOS_CLIENTES_VISUALIZADOS : 2,
      ULTIMOS_SOCIOS_VISUALIZADOS : 2,
      ULTIMOS_FORNECEDORES_VISUALIZADOS : 2,
      ULTIMOS_CLIENTES_INCLUIDOS : 1,
      ULTIMOS_SOCIOS_INCLUIDOS : 1,
      ULTIMOS_FORNECEDORES_INCLUIDOS : 1,
      ULTIMOS_ESTOQUE_INCLUIDOS : 1,
  }

  public PAGINATOR_SEMPRE : any = {
      USUARIOS : true,
      CLIENTES : true,
      SOCIOS : true,
  }


  public SALVAR_HISTORICO : any = {
      ADMINISTRADORES : true,
      ALUNOS : true,
      ANIVERSARIOS : true,
      ASSISTENTES : true,
      ATENDIMENTOS : true,
      BANCOS : true,
      CAIXA : true,
      CONCILIACAO : true,
      CONFIGURACAO : true,
      CONTAS : true,
      CONFIG_FINANCEIRO : true,
      VENDEDORES : true,
      DENTISTAS : true,
      DESPESAS : true,
      ENFERMEIROS : true,
      EQUIPE : true,
      MEDICOS : true,
      PROFISSIONAIS_DIVERSOS : true,
      FUNCIONARIOS_DIVERSOS : true,
      CLIENTES : true,
      SOCIOS : true,
	  FORNECEDORES : true,
      ESTOQUE : true,
      PAGAMENTOS : true,
      LANCAMENTOS_RECEITA : true,
      LANCAMENTOS_DESPESA : true,
      PERFIL : true,
      ORCAMENTOS : true,
      PROFESSORES : true,
      PROTETICOS : true,
      COMUNICADOS : true,
      RECEITAS : true,
      REVISOES : true,
      SECRETARIAS : true,
      TECNICOS : true,
      TRANSFERENCIAS : true,
      USUARIOS : true,
  }


  public SALVAR_REGISTRO_AUTOMATICO : any = {
      ATENDIMENTOS : true,
      BANCOS : true,
      CAIXA : true,
      CONCILIACAO : true,
      CONTAS : true,
      CONFIG_FINANCEIRO : true,
      DESPESAS : true,
      ORCAMENTOS : true,
      RECEITAS : true,
      TRANSFERENCIAS : true,
  }



  // public LISTA_ADMIN_PARA_OBSERVAR_RESERVADO =  [
      //     'observar_agenda',
      //     'observar_centros_de_custos',

      //     'observar_fornecedores',
      //     'observar_equipe',
      //     'observar_financeiro',
      //     'observar_historicos',
      //     'observar_impressos',
      //     'observar_indicador',
      //     'observar_movimentacao',
      //     'observar_clientes',
      //     'observar_estoque',
      //     'observar_rel_centros_de_custos',
      //     'observar_rel_cheque_pre',
      //     'observar_disponibilidade',
      //     'observar_rel_extrato_de_contas',
      //     'observar_relatorios',
      //     'observar_todos_pagamentos',
      //     'observar_usuarios',
      // ];


      public FIREBASE_LIST_OBSERVABLE : any = {
          ATENDIMENTOS : "atendimentos$",
          BANCOS : "bancos$",
          CAIXA : "caixa$",
          CENTROS_DE_CUSTOS : "centros_de_custos$",
          CONCILIACAO : "conciliacao$",
          CONTAS : "contas$",
          CONFIG_FINANCEIRO : "config_financeiro$",
          DESPESAS : "despesas$",
          FORNECEDORES : "fornecedores$",
          EQUIPE : "equipe$",
          FINANCEIRO : "financeiro$",
          HISTORICOS : "historicos$",
          IMPRESSOS : "impressos$",
          INDICADOR : "indicador$",
          MOVIMENTACAO : "movimentacao$",
          CLIENTES : "clientes$",
          SOCIOS : "socios$",
          ESTOQUE : "estoque$",
          PAGAMENTOS : "pagamentos$",
          LANCAMENTOS_RECEITA : "lancamentos_receita$",
          LANCAMENTOS_DESPESA : "lancamentos_despesa$",
          ORCAMENTOS : "orcamentos$",
          RECEITAS : "receitas$",
          REL_CENTROS_DE_CUSTOS : "rel_centros_de_custos$",
          REL_CHEQUES_PRE : "rel_cheque_pre$",
          REL_CHEQUES_A_VISTA : "rel_cheques_cheque$",
          DISPONIBILIDADE : "disponibilidade$",
          REL_EXTRATO_DE_CONTAS : "rel_extrato_de_contas$",
          RELATORIOS : "relatorios$",
          TRANSFERENCIAS : "transferencias$",
          ULTIMOS_CLIENTES_VISUALIZADOS : "clientes_ultimos_visualizados$",
          ULTIMOS_CLIENTES_INCLUIDOS : "estoque_ultimos_incluidos$",
          ULTIMOS_SOCIOS_VISUALIZADOS : "clientes_ultimos_visualizados$",
          ULTIMOS_SOCIOS_INCLUIDOS : "estoque_ultimos_incluidos$",
          ULTIMOS_FORNECEDORES_INCLUIDOS : "estoque_ultimos_incluidos$",
          ULTIMOS_ESTOQUE_INCLUIDOS : "estoque_ultimos_incluidos$",
          USUARIOS : "usuarios$",
      }


      public EXCLUIR_AUTOMATICO : any = {
          ADMINISTRADORES : "registros$",
          ALUNOS : "registros$",
          ASSISTENTES : "registros$",
          VENDEDORES : "registros$",
          DENTISTAS : "registros$",
          ENFERMEIROS : "registros$",
          PROFISSIONAIS_DIVERSOS : "registros$",
          MEDICOS : "registros$",
          FUNCIONARIOS_DIVERSOS : "registros$",
          PROFESSORES : "registros$",
          PROTETICOS : "registros$",
          SECRETARIAS : "registros$",
          TECNICOS : "registros$",
      }


      public classe_escolher_mes_do_ano_value : string[] = [
          'escolher_mes_do_ano_inativo',
          'escolher_mes_do_ano_inativo',
          'escolher_mes_do_ano_inativo',
          'escolher_mes_do_ano_inativo',
          'escolher_mes_do_ano_inativo',
          'escolher_mes_do_ano_inativo',
          'escolher_mes_do_ano_inativo',
          'escolher_mes_do_ano_inativo',
          'escolher_mes_do_ano_inativo',
          'escolher_mes_do_ano_inativo',
          'escolher_mes_do_ano_inativo',
          'escolher_mes_do_ano_inativo'
      ];

      // ===================================================



      // ===================================================
      // Constantes
      // ===================================================


      AGENDA : any = {
          retorno : "",
          database : "AGENDA",
          titulo_lista : "Agenda",
          titulo_unidade : "Agenda",
          singular : "evento",
          plural : "eventos",
      }

      ANIVERSARIOS : any = {
          retorno : "MALADIRETA",
          database : "CLIENTES",
          titulo_lista : "Aniversários",
          titulo_unidade : "Aniversariante",
          singular : "aniversário",
          plural : "aniversários",
          pode_incluir : false,
          pode_excluir : false,
          listar : "listar_aniversarios",
          selected : "selected_clientes",
          filtered : "filtered_aniversariantes",
          total_de : "total_de_aniversariantes",
      };

      REVISOES : any = {
          retorno : "MALADIRETA",
          database : "CLIENTES",
          titulo_lista : "Renovações e Revisões",
          titulo_unidade : "Renovações e Revisões",
          singular : "registro",
          plural : "registros",
      };

      COMUNICADOS : any = {
          retorno : "MALADIRETA",
          database : "CLIENTES",
          titulo_lista : "Comunicados",
          titulo_unidade : "Comunicado",
          singular : "comunicado",
          plural : "comunicados",
          pode_incluir : false,
          pode_excluir : false,
          pode_editar : false,
      };

      ULTIMOS_CLIENTES_VISUALIZADOS : any = {
          retorno : '',
          database : "ULTIMOS_CLIENTES_VISUALIZADOS",
          titulo_lista : "Últimos Acessados",
          titulo_unidade : "Registro",
          singular : "registro",
          plural : "registros",
          selected : "selected_clientes_ultimos_visualizados",
          key : true,
          nome : true,
          pode_editar : false,
          pode_incluir : false,
          pode_excluir : false,
          tem_sublista : false,
      };

      ULTIMOS_CLIENTES_INCLUIDOS : any = {
          retorno : '',
          database : "ULTIMOS_CLIENTES_INCLUIDOS",
          titulo_lista : "Últimos Incluídos",
          titulo_unidade : "Registro",
          singular : "registro",
          plural : "registros",
          selected : "selected_clientes_ultimos_incluidos",
          key : true,
          nome : true,
          pode_editar : false,
          pode_incluir : false,
          pode_excluir : false,
          tem_sublista : false,
      };


        ULTIMOS_SOCIOS_VISUALIZADOS : any = {
            retorno : '',
            database : "xULTIMOS_CLIENTES_VISUALIZADOS",
            titulo_lista : "Últimos Acessados",
            titulo_unidade : "Registro",
            singular : "registro",
            plural : "registros",
            selected : "selected_socios_ultimos_visualizados",
            key : true,
            nome : true,
            pode_editar : false,
            pode_incluir : false,
            pode_excluir : false,
            tem_sublista : false,
        };

        ULTIMOS_SOCIOS_INCLUIDOS : any = {
            retorno : '',
            database : "ULTIMOS_SOCIOS_INCLUIDOS",
            titulo_lista : "Últimos Incluídos",
            titulo_unidade : "Registro",
            singular : "registro",
            plural : "registros",
            selected : "selected_socios_ultimos_incluidos",
            key : true,
            nome : true,
            pode_editar : false,
            pode_incluir : false,
            pode_excluir : false,
            tem_sublista : false,
        };


      ULTIMOS_FORNECEDORES_INCLUIDOS : any = {
          retorno : '',
          database : "ULTIMOS_FORNECEDORES_INCLUIDOS",
          titulo_lista : "Últimos Incluídos",
          titulo_unidade : "Registro",
          singular : "registro",
          plural : "registros",
          selected : "selected_fornecedore_ultimos_incluidos",
          key : true,
          nome : true,
          pode_editar : false,
          pode_incluir : false,
          pode_excluir : false,
          tem_sublista : false,
      };

      ULTIMOS_ESTOQUE_INCLUIDOS : any = {
          retorno : '',
          database : "ULTIMOS_ESTOQUE_INCLUIDOS",
          titulo_lista : "Últimos Incluídos",
          titulo_unidade : "Registro",
          singular : "registro",
          plural : "registros",
          selected : "selected_estoque_ultimos_incluidos",
          key : true,
          nome : true,
          pode_editar : false,
          pode_incluir : false,
          pode_excluir : false,
          tem_sublista : false,
      };



      USUARIOS : any = {
          database : "USUARIOS",
          titulo_lista : "Usuários",
          titulo_unidade : "Usuário",
          singular : "usuário",
          plural : "usuários",
          listar : "listar_usuarios",
          selected : "selected_usuarios",
          key : true,
          celular : true,
          id : false,
          id_para_clientes : true,
          cep : true,
          cidade : true,
          cpf : true,
          email : true,
          endereco : true,
          bairro : true,
          estado : true,
          estadocivil : true,
          facebook : true,
          instagram : true,
          linkedin : true,
          identidade : true,
          img_url : true,
          indicacao : false,
          nacionalidade : true,
          nascimento : true,
          naturalidade : true,
          nome : true,
          obs: false,
          pode_incluir: false,
          pode_editar: false,
          pode_incluir_admin: false,
          pode_editar_admin: true,
          profissao: true,
          quando : true,
          quando_update : true,
          sexo : true,
          site : true,
          telefone : true,
          whatsapp : true,
      };

      PERFIL : any = {
          retorno : 'HOME',
          titulo_lista : "Meu Perfil",
          titulo_unidade : "Meu Perfil",
          singular : "registro",
          plural : "registros",
          key : true,
          celular : true,
          cep : true,
          cidade : true,
          cpf : true,
          email : true,
          endereco : true,
          bairro : true,
          estado : true,
          estadocivil : true,
          facebook : true,
          instagram : true,
          linkedin : true,
          identidade : true,
          img_url : true,
          indicacao : false,
          nacionalidade : true,
          nascimento : true,
          naturalidade : true,
          nome : true,
          titulo_profissional : true,
          obs: false,
          pode_incluir: false,
          pode_editar: true,
          pode_incluir_admin: true,
          pode_editar_admin: true,
          profissao: true,
          quando : true,
          quando_update : true,
          sexo : true,
          site : true,
          telefone : true,
          whatsapp : true,
      };


      CONFIGURACAO : any = {
          retorno : 'HOME',
          titulo_lista : "Configuração",
          titulo_unidade : "Configuração",
          id_para_clientes : true,
          titulo_profissional : true,
          cidade_default : true,
          estado_default : true,
          pode_incluir: false,
          pode_editar: true,
          pode_incluir_admin: false,
          pode_editar_admin: false,
          quando : true,
          quando_update : true,
      };


      CLIENTES : any = {
          database : "CLIENTES",
          titulo_lista : "Clientes",
          titulo_unidade : "Cliente",
          singular : "cliente",
          plural : "clientes",
          listar : "listar_clientes",
          selected : "selected_clientes",
          filtered : "filtered_clientes",
          total_de : "total_de_clientes",
		  ref : "ref_clientes",
		  ultimos_incluidos : "ref_clientes_ultimos_incluidos",
		  ultimos_visualizados : "ref_clientes_ultimos_visualizados",
          key : true,
          id : true,
          label_id : "ID",
          nome : true,
          label_nome : "Cliente",
          razaosocial : true,
          celular : true,
          cep : true,
          cidade : true,
          cpf : true,
          cnpj : true,
          email : true,
          endereco : true,
          bairro : true,
          estado : true,
          estadocivil : true,
          identidade : true,
          img_url : true,
          indicacao : true,
          nacionalidade : true,
          nascimento : true,
          naturalidade : true,
          obs: true,
          label_obs: "Obs",
          pode_incluir : true,
          pode_excluir : true,
          pode_editar : true,
          profissao: true,
          quando : true,
          quando_update : true,
          sexo : true,
          site : true,
          telefone : true,
          whatsapp : true,
          facebook : true,
          instagram : true,
          criado_em : false,
          label_criado : "Incluído",
          modificado_em : true,
          revisao : false,
          reativar : true,
          ultima_consulta : true,
          msg_aniversario_enviada : true,
          msg_revisao_enviada : true,
          msg_promocao_enviada : true,
      };


    SOCIOS : any = {
        database : "SOCIOS",
        titulo_lista : "Socios",
        titulo_unidade : "Socio",
        singular : "sócio",
        plural : "sócios",
        listar : "listar_socios",
        selected : "selected_socios",
        filtered : "filtered_socios",
        total_de : "total_de_socios",
		ref : "ref_socios",
		ultimos_incluidos : "ref_socios_ultimos_incluidos",
		ultimos_visualizados : "ref_socios_ultimos_visualizados",
        key : true,
        id : true,
        label_id : "ID",
        celular : true,
        cep : true,
        cidade : true,
        cpf : true,
        cnpj : true,
        email : true,
        endereco : true,
        bairro : true,
        estado : true,
        estadocivil : true,
        identidade : true,
        img_url : true,
        indicacao : true,
        nacionalidade : true,
        nascimento : true,
        naturalidade : true,
        nome : true,
        label_nome : "Socio",
        razaosocial : true,
        obs: true,
        label_obs: "Obs",
        pode_incluir : true,
        pode_excluir : true,
        pode_editar : true,
        profissao: true,
        quando : true,
        quando_update : true,
        sexo : true,
        site : true,
        telefone : true,
        whatsapp : true,
        facebook : true,
        instagram : true,
        criado_em : false,
        label_criado : "Incluído",
        modificado_em : true,
        revisao : false,
        reativar : true,
        ultima_consulta : true,
        msg_aniversario_enviada : true,
        msg_revisao_enviada : true,
        msg_promocao_enviada : true,
    };

    EQUIPE : any = {
      retorno : '',
      database : "EQUIPE",
      titulo_lista : "Equipe",
      titulo_unidade : "Equipe",
      listar : "listar_equipe",
      selected : "selected_equipe",
      filtered : "filtered_equipe",
      total_de : "total_de_equipe",
      ref : "ref_equipe",
      ultimos_incluidos : "ref_equipe_ultimos_incluidos",
      singular : "registro",
      plural : "registros",
      key : true,
      id : false,
      label_id : "ID",
      nome : true,
      label_nome : "Cliente",
      razaosocial : false,
      cep : true,
      cidade : true,
      bairro : true,
      descricao : true,
      email : true,
      emailcorporativo : true,
      senha_emailcorporativo : true,
      endereco : true,
      estado : true,
      facebook : true,
      instagram : true,
      linkedin : true,
      img_url : true,
      obs: true,
      cpf : true,
      cnpj : true,
      especialidade : true,
      nascimento : true,
      funcao : true,
      quando : true,
      quando_update : true,
      sexo : true,
      site : true,
      telefone : true,
      whatsapp : true,
      profissao : true,
      pode_incluir : true,
      pode_excluir : true,
      pode_editar : true,
    };


      ORCAMENTOS : any = {
          retorno : 'CLIENTES',
          database : "ORCAMENTOS",
          titulo_lista : "Orçamentos",
          titulo_unidade : "Orçamento",
          singular : "registro",
          plural : "registros",
          listar : "listar_orcamentos",
          selected : "selected_orcamentos",
          filtered : "filtered_orcamentos",
          total_de : "total_de_orcamentos",
		  ref : "ref_orcamentos",
          criado_em : true,
          modificado_em : true,
          nome : true,
          cliente_nome : true,
          label_nome : "Descrição curta",
          data : true,
          obs : true,
          label_obs : "Plano",
          valor_do_tratamento : true,
          label_valor_do_tratamento : "Valor",
          saldo : true,
          centro_de_custos: true,
          centro_de_custos_codigo : true,
          label_forma_de_pagamento : "Como pagar",
          pode_incluir : true,
          pode_excluir : true,
          pode_editar : true,
          exames_planos_ou_historicos_do_cliente : true,
      };

      PAGAMENTOS : any = {
          retorno : 'CLIENTES',
          database : "LANCAMENTOS_RECEITA",
          titulo_lista : "Pagamentos",
          titulo_unidade : "Pagamentos",
          singular : "pagamento",
          plural : "pagamentos",
          listar : "listar_pagamentos",
          selected : "selected_pagamentos",
		  filtered : "filtered_pagamentos",
		  total_de : "total_de_pagamentos",
		  ref : "ref_pagamentos",
          criado_em : true,
          label_criado : "Registrado",
          modificado_em : true,
          nome : false,
          label_nome : "Descrição",
          cliente_nome : true,
          cliente_cpf : true,
          pagamento : true,
          atendimento : false,
          profissional_nome : true,
          profissional_cpf : true,
          profissional_key : true,
          profissional_profissao : true,
          cpf : false,
          valor : true,
          recebido : false,
          tipo_de_desconto : false,
          clinica : true,
          responsavel : false,
          obs : true,
          img_url : false,
          pode_incluir : true,
          pode_excluir : true,
          pode_editar : false,
          tem_sublista : false,
          pode_fazer_upload : true,
          exames_planos_ou_historicos_do_cliente : true,
      };


      LANCAMENTOS_DESPESA : any = {
          retorno : 'FINANCEIRO',
          database : "LANCAMENTOS_DESPESA",
          titulo_lista : "Despesas",
          titulo_unidade : "Despesa",
          singular : "lançamento",
          plural : "lançamentos",
          listar : "listar_lancamentos_despesa",
          selected : "selected_lancamentos_despesa",
          filtered : "filtered_lancamentos_despesa",
          filtered_bom_para : "filtered_lancamentos_despesa_bom_para",
          total_de : "total_de_lancamentos_despesa",
          ref : "ref_lancamentos_despesa",
          criado_em : true,
          label_criado : "Registrado",
          modificado_em : true,
          centro_de_custos : true,
          centro_de_custos_codigo : true,
          produto : true,
          nome : true,
          label_nome : "Produto",
          img_url : true,
          listar_imagens : true,
          data : true,
          cpf : false,
          contraparte : true,
          label_contraparte : "Recebedor",
          contraparte_cpf : true,
          contraparte_cnpj : true,
          contraparte_key : true,
          meio_de_pagamento : true,
          data_cheque_pre : true,
          data_credito : true,
          cheque_numero : true,
          banco : true,
          agencia : true,
          conta : true,
          pagamento : true,
          atendimento : false,
          quantidade : true,
          valor : true,
          recebido : false,
          clinica : true,
          responsavel : false,
          incluir_no_estoque : true,
          codigo_no_estoque : true,
          obs : true,
          pode_incluir : true,
          pode_excluir : true,
          pode_editar : true,
          tem_sublista : false,
          pode_fazer_upload : true,
          exames_planos_ou_historicos_do_cliente : false,
          quitado : true,
          fechado : true,
      };

      LANCAMENTOS_RECEITA : any = {
          retorno : 'FINANCEIRO',
          database : "LANCAMENTOS_RECEITA",
          titulo_lista : "Receitas",
          titulo_unidade : "Receita",
          singular : "lançamento",
          plural : "lançamentos",
          listar : "listar_lancamentos_receita",
          selected : "selected_lancamentos_receita",
          filtered : "filtered_lancamentos_receita",
          filtered_bom_para : "filtered_lancamentos_receita_bom_para",
          total_de : "total_de_lancamentos_receita",
          ref : "ref_lancamentos_receita",
          criado_em : true,
          label_criado : "Registrado",
          modificado_em : true,
          centro_de_custos : true,
          centro_de_custos_codigo : true,
          produto : true,
          nome : true,
          label_nome : "Produto",
          img_url : true,
          listar_imagens : true,
          data : true,
          cpf : false,
          contraparte : true,
          label_contraparte : "Pagador",
          contraparte_cpf : true,
          contraparte_cnpj : true,
          contraparte_key : true,
          meio_de_pagamento : true,
          data_cheque_pre : true,
          data_credito : true,
          cheque_numero : true,
          banco : true,
          agencia : true,
          conta : true,
          pagamento : true,
          pagamento_quando : true,
          profissional_nome : true,
          profissional_cpf : true,
          profissional_key : true,
          profissional_profissao : true,
          atendimento : false,
          quantidade : true,
          valor_unitario : true,
          valor : true,
          recebido : false,
          clinica : true,
          responsavel : false,
          obs : true,
          orcamento : true,
          label_orcamento : 'Orçamento',
          pode_incluir : true,
          pode_excluir : true,
          pode_editar : true,
          tem_sublista : false,
          exames_planos_ou_historicos_do_cliente : false,
          quitado : true,
          fechado : true,
      };

      REL_RECEITAS_E_DESPESAS : any = {
          retorno : 'RELATORIOS',
          database : "REL_RECEITAS_E_DESPESAS",
          titulo_lista : "Receitas e Despesas Detalhadas",
          titulo_unidade : "Receitas e Despesas Detalhadas",
          singular : "registro",
          plural : "registros",
          listar : "listar_rel_receitas_e_despesas",
          criado_em : true,
          criado_quando : true,
          criado_por_key : true,
          criado_por_nome : true,
          data : true,
          data_quando : true,
          meio_de_pagamento : true,
          modificado_em : true,
          modificado_quando : true,
          modificado_por_key : true,
          modificado_por_nome : true,
          label_criado : "Registrado",
          nome : true,
          label_nome : "Descrição",
          img_url : true,
          centro_de_custos : true,
          produto : true,
          quantidade : true,
          pagamento : true,
          pagamento_quando : true,
          profissional_nome : true,
          profissional_cpf : true,
          profissional_key : true,
          profissional_profissao : true,
          valor : true,
          banco : true,
          agencia : true,
          cheque_numero : true,
          conta : true,
          quitado : true,
          contraparte : true,
          label_contraparte : 'Contraparte',
          contraparte_cpf : true,
          obs : true,
      };


      ESTOQUE : any = {
          database : "ESTOQUE",
          titulo_lista : "Estoque",
          titulo_unidade : "Estoque",
          singular : "registro",
          plural : "registros",
          listar : "listar_estoque",
          selected : "selected_estoque",
          filtered : "filtered_estoque",
          total_de : "total_de_estoque",
		  ref : "ref_estoque",
		  ultimos_incluidos : "ref_estoque_ultimos_incluidos",
          key : true,
          id : true,
          codigodebarras : true,
          nome : true,
          label_nome : 'Nome',
          categoria : true,
          descricao : true,
          material : true,
          cor : true,
          img_url : true,
          listar_imagens : true,
          url : true,
          preco_custo : true,
          preco_venda : true,
          unidade : false,
          quantidade : true,
          quantidade_minima : true,
          quantidade_maxima : true,
          obs: true,
          pode_incluir : true,
          pode_excluir : true,
          pode_editar : true,
          quando : true,
          quando_update : true,
          criado_em : true,
          label_criado : "Registrado",
          modificado_em : true,
      };


      ATENDIMENTOS : any = {
          database : "ATENDIMENTOS",
          titulo_lista : "Atendimentos",
          titulo_unidade : "Atendimento",
          singular : "atendimento",
          plural : "atendimentos",
          listar : "listar_atendimentos",
          selected : "selected_atendimentos",
          filtered : "filtered_atendimentos",
          total_de : "total_de_atendimentos",
          criado_em : true,
          modificado_em : true,
          nome : true,
          label_nome : "Descrição",
          cliente : true,
          responsavel : true,
          data : true,
          data_inicio : true,
          data_termino : true,
		  hora : true,
		  hora_inicio : true,
		  hora_termino : true,
          objetivo : true,
          urgencia : true,
          status : true,
          obs : true,
          pode_fazer_upload : false,
          tem_sublista : false,
          pode_incluir : true,
          pode_excluir : true,
          pode_editar : true,
      };


      HISTORICOS : any = {
          retorno : '',
          database : "HISTORICOS",
          titulo_lista : "Histórico",
          titulo_unidade : "Histórico",
          singular : "registro",
          plural : "registros",
          listar : "listar_historicos",
          selected : "selected_historicos",
          filtered : "filtered_historicos",
          total_de : "total_de_historicos",
		  ref : "ref_historicos",
          criado_em : true,
          label_criado_em : "Quando",
          label_criado_por_nome : "Por quem",
          modificado_em : true,
          obs : true,
          pode_incluir : false,
          pode_excluir : false,
          pode_editar : false,
      };


      INDICADOR : any = {
          retorno : '',
          database : "INDICADOR",
          database_raiz : "ADMIN",
          titulo_lista : "Indicador",
          titulo_unidade : "Indicador",
          listar : "listar_indicador",
          selected : "selected_indicadores",
          pode_editar : false,
          pode_incluir : false,
          pode_excluir : false,
          tem_sublista : true,
      };

      FINANCEIRO : any = {
          retorno : '',
          database_raiz : "ADMIN",
          database : "FINANCEIRO",
          titulo_lista : "Financeiro",
          titulo_unidade : "Financeiro",
          listar : "listar_financeiro",
          selected : "selected_financeiro",
          filtered : "filtered_financeiro",
          total_de : "total_de_financeiro",
          pode_editar : false,
          pode_incluir : false,
          pode_excluir : false,
          tem_sublista : true,
      };


      CENTROS_DE_CUSTOS : any = {
		  retorno : 'FINANCEIRO',
          database_raiz : "ADMIN",
          database : "CENTROS_DE_CUSTOS",
          titulo_lista : "Configurar Centros de Custos",
          titulo_unidade : "Centro de Custos",
          listar : "listar_centros_de_custos",
          selected : "selected_centros_de_custos",
          pode_editar : false,
          pode_incluir : false,
          pode_excluir : false,
          tem_sublista : true,
      };



      CONTAS : any = {
          retorno : 'FINANCEIRO',
          database_raiz : "ADMIN",
          database : "CONTAS",
          titulo_lista : "Contas",
          titulo_unidade : "Conta",
          listar : "listar_contas",
          selected : "selected_contas",
          pode_incluir : false,
          pode_excluir : false,
          pode_editar : false,
          tem_sublista : true,
      };

      CONFIG_FINANCEIRO : any = {
          retorno : 'FINANCEIRO',
          database_raiz : "ADMIN",
          database : "CONFIG_FINANCEIRO",
          titulo_lista : "Configuração Financeira",
          titulo_unidade : "Configuração Financeira",
          listar : "listar_config_financeiro",
          selected : "selected_config_financeiro",
		  filtered : "filtered_config_financeiro",
		  total_de : "total_de_config_financeiro",
		  nome : true,
          pode_incluir : false,
          pode_excluir : false,
          pode_editar : false,
          tem_sublista : true,
      };


      BANCOS : any = {
          retorno : 'FINANCEIRO',
          database : "BANCOS",
          titulo_lista : "Bancos",
          titulo_unidade : "Conta Bancária",
          singular : "registro",
          plural : "registros",
          listar : "listar_bancos",
          selected : "selected_bancos",
          filtered : "filtered_bancos",
          total_de : "total_de_bancos",
		  ref : "ref_bancos",
          criado_em : true,
          modificado_em : true,
          nome : true,
          label_nome : "Banco",
          agencia : true,
          conta : true,
          corrente : true,
          gerente : true,
          tel_contato : true,
          obs : true,
          label_obs : "Obs",
          pode_fazer_upload : false,
          tem_sublista : false,
          img_url : false,
          pode_incluir : true,
          pode_excluir : true,
          pode_editar : true,
      };


      REL_BANCOS : any = {
          retorno : 'RELATORIOS',
          database : "BANCOS",
          titulo_lista : "Contas Bancárias",
          titulo_unidade : "Conta Bancária",
          singular : "registro",
          plural : "registros",
          listar : "listar_rel_bancos",
          selected : "selected_rel_bancos",
		  filtered : "filtered_rel_bancos",
		  total_de : "total_de_rel_bancos",
          criado_em : true,
          modificado_em : true,
          nome : true,
          label_nome : "Banco",
          apelido : false,
          label_apelido : "Apelido",
          agencia : true,
          conta : true,
          corrente : true,
          saldo : true,
          pode_editar_saldo : false,
          obs : true,
          label_obs : "Obs",
          pode_fazer_upload : false,
          tem_sublista : false,
          img_url : false,
          pode_incluir : true,
          pode_excluir : true,
          pode_editar : true,
      };

      CODIGOS_DE_BANCOS : any = {
          retorno : 'RELATORIOS',
          database_raiz : "ADMIN",
          database : "CODIGOS_DE_BANCOS",
          titulo_lista : "Bancos",
          titulo_unidade : "Banco",
          listar : "listar_bancos",
          selected : "selected_codigos_de_bancos",
		  filtered : "filtered_codigos_de_bancos",
          total_de : "total_de_codigos_de_bancos",
          nome : true,
          codigo : true,
          pode_editar : false,
          pode_incluir : false,
          pode_excluir : false,
      }

      MOVIMENTACAO : any = {
          retorno : 'FINANCEIRO',
          database_raiz : "ADMIN",
          database : "MOVIMENTACAO",
          titulo_lista : "Movimentação Financeira",
          titulo_unidade : "Movimentação Financeira",
          listar : "listar_movimentacao",
          selected : "selected_movimentacao",
		  filtered : "filtered_movimentacao",
          total_de : "total_de_movimentacao",
          pode_editar : false,
          pode_incluir : false,
          pode_excluir : false,
          tem_sublista : true,
      };

      RELATORIOS : any = {
          retorno : 'FINANCEIRO',
          database_raiz : "ADMIN",
          database : "RELATORIOS",
          titulo_lista : "Relatórios Financeiros",
          titulo_unidade : "Relatório Financeiro",
          listar : "listar_relatorios",
          selected : "selected_relatorios",
          filtered : "filtered_relatorios",
          total_de : "total_de_relatorios",
          pode_editar : false,
          pode_incluir : false,
          pode_excluir : false,
          tem_sublista : true,
      };


      CAIXA : any = {
          retorno : 'FINANCEIRO',
          database : "CAIXA",
          database_raiz : "ADMIN",
          titulo_lista : "Caixa",
          titulo_unidade : "Caixa",
          singular : "registro",
          plural : "registros",
          selected : "selected_caixa",
          filtered : "filtered_caixa",
          total_de : "total_de_caixa",
          pode_incluir : false,
          pode_excluir : false,
          pode_editar : false,
          tem_sublista : true,
      };

      REL_EXTRATO_DE_CONTAS : any = {
          retorno : 'RELATORIOS',
          database : "REL_EXTRATO_DE_CONTAS",
          titulo_lista : "Extrato de Contas",
          titulo_unidade : "Extrato de Contas",
          listar : "listar_rel_extrato_de_contas",
          selected : "selected_rel_extrato_de_contas",
		  filtered : "filtered_rel_extrato_de_contas",
          total_de : "total_de_rel_extrato_de_contas",
          pode_editar : false,
          pode_incluir : false,
          pode_excluir : false,
          tem_sublista : true,
      };


      RESULTADOS : any = {
          retorno : 'RELATORIOS',
          database : "RESULTADOS",
          titulo_lista : "Resultado Financeiro",
          titulo_unidade : "Resultado Financeiro",
          listar : "listar_resultados",
          selected : "selected_resultados",
          filtered : "filtered_resultados",
          total_de : "total_de_resultados",
          criado_em : true,
          label_criado : "Registrado",
          modificado_em : true,
          centro_de_custos : true,
          centro_de_custos_codigo : true,
          produto : true,
          nome : true,
          label_nome : "Referência",
          img_url : true,
          listar_imagens : true,
          data : true,
          cpf : false,
          contraparte : true,
          label_contraparte : "Pagador",
          contraparte_cpf : true,
          contraparte_cnpj : true,
          contraparte_key : true,
          meio_de_pagamento : true,
          data_cheque_pre : true,
          data_credito : true,
          cheque_numero : true,
          banco : true,
          agencia : true,
          conta : true,
          pagamento : true,
          pagamento_quando : true,
          profissional_nome : true,
          profissional_cpf : true,
          profissional_key : true,
          profissional_profissao : true,
          atendimento : false,
          valor : true,
          quantidade : true,
          recebido : false,
          clinica : true,
          responsavel : false,
          obs : true,
          orcamento : true,
          label_orcamento : 'Orçamento',
          pode_editar : false,
          pode_incluir : false,
          pode_excluir : false,
          tem_sublista : false,
      };


      REL_CENTROS_DE_CUSTOS : any = {
          retorno : 'RELATORIOS',
          database : "REL_CENTROS_DE_CUSTOS",
          titulo_lista : "Centros de Custos",
          titulo_unidade : "Centros de Custos",
          listar : "listar_rel_centros_de_custos",
          selected : "selected_rel_centros_de_custos",
		  filtered : "filtered_rel_centros_de_custos",
		  total_de : "total_de_rel_centros_de_custos",
          pode_editar : false,
          pode_incluir : false,
          pode_excluir : false,
          tem_sublista : true,
      };


      REL_CENTROS_DE_CUSTOS_TOTALIZADOS : any = {
          retorno : 'RELATORIOS',
          titulo_lista : "Centros de Custos Totalizados",
          titulo_unidade : "Centros de Custos Totalizados",
          singular : "registro",
          plural : "registros",
          listar : "listar_rel_centros_de_custos_totalizados",
		  selected : "selected_rel_centros_de_custos_totalizados",
		  filtered : "filtered_rel_centros_de_custos_totalizados",
		  total_de : "total_de_rel_centros_de_custos_totalizados",
          key : true,
          nome : true,
          pode_editar : false,
          pode_incluir : false,
          pode_excluir : false,
          pode_editar_admin : true,
          pode_incluir_admin : true,
          tem_sublista : false,
      };


      CENTROS_DE_CUSTOS_LISTA : any = {
          retorno : 'RELATORIOS',
          database : "CENTROS_DE_CUSTOS_LISTA",
          titulo_lista : "Centros de Custos",
          titulo_unidade : "Centro de Custos",
          listar : "listar_centros_de_custos_lista",
          selected : "selected_centros_de_custos_lista",
		  filtered : "filtered_centros_de_custos_lista",
		  total_de : "total_de_centros_de_custos_lista",
          singular : 'centro de custos',
          plural : 'centros de custos',
          pode_editar : false,
          pode_incluir : false,
          pode_excluir : false,
          tem_sublista : true,
      };




      REL_DINHEIRO : any = {
          retorno : 'CAIXA',
          titulo_lista : "Caixa - Dinheiro",
          titulo_unidade : "Dinheiro",
          singular : "registro",
          plural : "registros",
          listar : "listar_rel_dinheiro",
          selected : "selected_rel_dinheiro",
		  filtered : "filtered_rel_dinheiro",
		  total_de : "total_de_rel_dinheiro",
          key : true,
          nome : true,
          label_nome : "Referência",
          centro_de_custos : true,
          centro_de_custos_codigo : true,
          data : true,
          cpf : false,
          contraparte : true,
          label_contraparte : "Pagador",
          contraparte_cpf : true,
          contraparte_cnpj : true,
          contraparte_key : true,
          meio_de_pagamento : true,
          cheque_numero : true,
          banco : true,
          agencia : true,
          conta : true,
          pagamento : true,
          profissional_nome : true,
          profissional_cpf : true,
          profissional_key : true,
          profissional_profissao : true,
          atendimento : false,
          valor : true,
          recebido : false,
          clinica : true,
          responsavel : false,
          obs : true,
          img_url : false,
          orcamento : true,
          label_orcamento : 'Orçamento',
          quitado : true,
          fechado : true,
          pode_editar : false,
          pode_incluir : false,
          pode_excluir : false,
          tem_sublista : false,
      };



    REL_DEBITO : any = {
        retorno : 'CAIXA',
        titulo_lista : "Caixa - Cartão de Débito",
        titulo_unidade : "Cartões de Débito",
        singular : "registro",
        plural : "registros",
        listar : "listar_rel_debito",
        selected : "selected_rel_debito",
    	  filtered : "filtered_rel_debito",
    	  total_de : "total_de_rel_debito",
        key : true,
        nome : true,
        label_nome : "Referência",
        centro_de_custos : true,
        centro_de_custos_codigo : true,
        data : true,
        cpf : false,
        contraparte : true,
        label_contraparte : "Pagador",
        contraparte_cpf : true,
        contraparte_cnpj : true,
        contraparte_key : true,
        meio_de_pagamento : true,
        cheque_numero : true,
        banco : true,
        agencia : true,
        conta : true,
        pagamento : true,
        profissional_nome : true,
        profissional_cpf : true,
        profissional_key : true,
        profissional_profissao : true,
        atendimento : false,
        valor : true,
        recebido : false,
        clinica : true,
        responsavel : false,
        obs : true,
        img_url : false,
        orcamento : true,
        label_orcamento : 'Orçamento',
        quitado : true,
        fechado : true,
        pode_editar : false,
        pode_incluir : false,
        pode_excluir : false,
        tem_sublista : false,
    };


    REL_CHEQUES_A_VISTA : any = {
          retorno : 'CAIXA',
          database_raiz : "ADMIN",
          database : "REL_CHEQUES_A_VISTA",
          titulo_lista : "Caixa - Cheques à Vista",
          titulo_unidade : "Caixa - Cheques à Vista",
          singular : "registro",
          plural : "registros",
          listar : "listar_rel_cheque",
          selected : "selected_rel_cheque",
          filtered : "filtered_rel_cheque",
          total_de : "total_de_rel_cheque",
          key : true,
          nome : true,
          label_nome : "Referência",
          centro_de_custos : true,
          centro_de_custos_codigo : true,
          data : true,
          cpf : false,
          contraparte : true,
          label_contraparte : "Pagador",
          contraparte_cpf : true,
          contraparte_cnpj : true,
          contraparte_key : true,
          meio_de_pagamento : true,
          cheque_numero : true,
          banco : true,
          agencia : true,
          conta : true,
          pagamento : true,
          profissional_nome : true,
          profissional_cpf : true,
          profissional_key : true,
          profissional_profissao : true,
          atendimento : false,
          valor : true,
          recebido : false,
          clinica : true,
          responsavel : false,
          obs : true,
          img_url : false,
          orcamento : true,
          label_orcamento : 'Orçamento',
          quitado : true,
          fechado : true,
          pode_editar : false,
          pode_incluir : false,
          pode_excluir : false,
          tem_sublista : false,
    };


    REL_CHEQUES_PRE : any = {
          retorno : 'CAIXA',
          database_raiz : "ADMIN",
          database : "REL_CHEQUES_PRE",
          titulo_lista : "Caixa - Cheques Pré",
          titulo_unidade : "Caixa - Cheques Pré",
          singular : "registro",
          plural : "registros",
          listar : "listar_rel_cheque_pre",
          selected : "selected_rel_cheque_pre",
          filtered : "filtered_rel_cheque_pre",
		  total_de : "total_de_rel_cheque_pre",
          key : true,
          nome : true,
          label_nome : "Referência",
          centro_de_custos : true,
          centro_de_custos_codigo : true,
          data : true,
          data_cheque_pre : true,
          cpf : false,
          contraparte : true,
          label_contraparte : "Pagador",
          contraparte_cpf : true,
          contraparte_cnpj : true,
          contraparte_key : true,
          meio_de_pagamento : true,
          cheque_numero : true,
          banco : true,
          agencia : true,
          conta : true,
          pagamento : true,
          profissional_nome : true,
          profissional_cpf : true,
          profissional_key : true,
          profissional_profissao : true,
          atendimento : false,
          valor : true,
          recebido : false,
          clinica : true,
          responsavel : false,
          obs : true,
          img_url : false,
          orcamento : true,
          label_orcamento : 'Orçamento',
          quitado : true,
          fechado : true,
          pode_editar : false,
          pode_incluir : false,
          pode_excluir : false,
          tem_sublista : false,
    };


    REL_CREDITO : any = {
        retorno : 'CAIXA',
        database_raiz : "ADMIN",
        database : "REL_CREDITO",
        titulo_lista : "Caixa - Cartão de Crédito",
        titulo_unidade : "Cartões de Crédito",
        singular : "registro",
        plural : "registros",
        listar : "listar_rel_credito",
        selected : "selected_rel_credito",
        filtered : "filtered_rel_credito",
        filtered_bom_para : "filtered_rel_credito_bom_para",
        total_de : "total_de_rel_credito",
        key : true,
        nome : true,
        label_nome : "Referência",
        centro_de_custos : true,
        centro_de_custos_codigo : true,
        data : true,
        data_credito : true,
        cpf : false,
        contraparte : true,
        label_contraparte : "Pagador",
        contraparte_cpf : true,
        contraparte_cnpj : true,
        contraparte_key : true,
        meio_de_pagamento : true,
        cheque_numero : true,
        banco : true,
        agencia : true,
        conta : true,
        pagamento : true,
        profissional_nome : true,
        profissional_cpf : true,
        profissional_key : true,
        profissional_profissao : true,
        atendimento : false,
        valor : true,
        recebido : false,
        clinica : true,
        responsavel : false,
        obs : true,
        img_url : false,
        orcamento : true,
        label_orcamento : 'Orçamento',
        quitado : true,
        fechado : true,
        pode_editar : false,
        pode_incluir : false,
        pode_excluir : false,
        tem_sublista : false,
    };




      PRODUCAO_PROFISSIONAL : any = {
          retorno : 'RELATORIOS',
          titulo_lista : "Comissionamentos",
          titulo_unidade : "Comissionamentos",
          key : true,
          nome : true,
          label_nome : "Referência",
          centro_de_custos : true,
          centro_de_custos_codigo : true,
          data : true,
          cpf : false,
          contraparte : true,
          label_contraparte : "Pagador",
          contraparte_cpf : true,
          contraparte_cnpj : true,
          contraparte_key : true,
          meio_de_pagamento : true,
          cheque_numero : true,
          data_cheque_pre : true,
          banco : true,
          agencia : true,
          conta : true,
          pagamento : true,
          profissional_nome : true,
          profissional_cpf : true,
          profissional_key : true,
          profissional_profissao : true,
          atendimento : false,
          valor : true,
          recebido : false,
          clinica : true,
          responsavel : false,
          obs : true,
          img_url : false,
          orcamento : true,
          label_orcamento : 'Orçamento',
          quitado : true,
          fechado : true,
          pode_editar : false,
          pode_incluir : false,
          pode_excluir : false,
          tem_sublista : false,
      }


      DISPONIBILIDADE : any = {
          retorno : 'RELATORIOS',
          database : "DISPONIBILIDADE",
          titulo_lista : "Disponibilidade Financeira",
          titulo_unidade : "Disponibilidade Financeira",
          singular : "registro",
          plural : "registros",
          listar : "listar_disponibilidade",
          selected : "selected_disponibilidade",
		  filtered : "filtered_disponibilidade",
		  total_de : "total_de_disponibilidade",
          key : true,
          nome : true,
          pode_editar : false,
          pode_incluir : false,
          pode_excluir : false,
          pode_editar_admin : true,
          pode_incluir_admin : true,
          tem_sublista : false,
      };

      COMPARTILHAMENTOS_GEOLOCALIZACAO : any = {
          database : "COMPARTILHAMENTOS_GEOLOCALIZACAO",
          titulo_lista : "Geolocalização",
          titulo_unidade : "Geolocalização",
          singular : 'registro',
          plural : 'registros',
          listar : "listar_geo",
          selected : "selected_geo",
          filtered : "filtered_geo",
          total_de : "total_de_geo",
          ref : "ref_geo",
          criado_em : true,
          email_responsavel : true,
          email_cliente : true,
          latitude : true,
          longitude : true,
          acuracia : true,
          timestamp : true,
          pode_incluir : true,
          pode_excluir : true,
          pode_editar : true,
     };


      RECEITAS : any = {
          retorno : 'CENTROS_DE_CUSTOS',
          database : "RECEITAS",
          titulo_lista : "Configurar Receitas",
          titulo_unidade : "Receita",
          singular : 'centro de custos',
          plural : 'centros de custos',
          listar : "listar_receitas",
          selected : "selected_receitas",
          filtered : "filtered_receitas",
          total_de : "total_de_receitas",
          criado_em : true,
          modificado_em : true,
          id : true,
          label_id : "Código",
          nome : true,
          label_nome : "Nome",
          obs : true,
          img_url : false,
          pode_incluir : true,
          pode_excluir : true,
          pode_editar : true,
      };


      DESPESAS : any = {
          retorno : 'CENTROS_DE_CUSTOS',
          database : "DESPESAS",
          titulo_lista : "Configurar Despesas",
          titulo_unidade : "Despesa",
          singular : 'centro de custos',
          plural : 'centros de custos',
          listar : "listar_despesas",
          selected : "selected_despesas",
          filtered : "filtered_despesas",
          total_de : "total_de_despesas",
          criado_em : true,
          modificado_em : true,
          id : true,
          label_id : "Código",
          nome : true,
          label_nome : "Nome",
          obs : true,
          label_obs : "Descrição",
          img_url : false,
          pode_incluir : true,
          pode_excluir : true,
          pode_editar : true,
      };


      TRANSFERENCIAS : any = {
          retorno : 'FINANCEIRO',
          database : "TRANSFERENCIAS",
          database_raiz : "ADMIN",
          titulo_lista : "Movimentação Financeira",
          titulo_unidade : "Movimentação Financeira",
          listar : "listar_transferencias",
          selected : "selected_transferencias",
          pode_incluir : false,
          pode_excluir : false,
          pode_editar : false,
          tem_sublista : true,
      };

      CONCILIACAO : any = {
          retorno : 'FINANCEIRO',
          database : "CONCILIACAO",
          titulo_lista : "Conciliação Bancária",
          titulo_unidade : "Conciliação Bancária",
          singular : "registro",
          plural : "registros",
          listar : "listar_conciliacao",
          selected : "selected_conciliacao",
          criado_em : true,
          modificado_em : true,
          nome : true,
          label_nome : "Descrição",
          data : true,
          obs : true,
          pode_fazer_upload : false,
          tem_sublista : false,
          img_url : false,
          pode_incluir : true,
          pode_excluir : true,
          pode_editar : true,
          exames_planos_ou_historicos_do_cliente : true,
      };


      FORNECEDORES : any = {
          retorno : '',
          database : "FORNECEDORES",
          titulo_lista : "Fornecedores",
          titulo_unidade : "Fornecedores",
          listar : "listar_fornecedores",
          selected : "selected_fornecedores",
          filtered : "filtered_fornecedores",
          total_de : "total_de_fornecedores",
          ref : "ref_fornecedores",
          ultimos_incluidos : "ref_fornecedores_ultimos_incluidos",
          cep : true,
          cidade : true,
          bairro : true,
          descricao : true,
          email : true,
          endereco : true,
          especialidades : false,
          estado : true,
          facebook : true,
          instagram : true,
          linkedin : true,
          nome : true,
          razaosocial : true,
          obs: true,
          sexo : true,
          nascimento : true,
          img_url : true,
          site : true,
          cpf : true,
          cnpj : true,
          inscricaoestadual : true,
          telefone : true,
          contatos : true,
          whatsapp : true,
          produtos : true,
          quando : true,
          quando_update : true,
          pode_editar : true,
          pode_incluir : true,
          pode_excluir : true,
          tem_sublista : false,
      };



      EMPRESAS : any = {
          retorno : '',
          database : "EMPRESAS",
          database_raiz : "ADMIN",
          titulo_lista : "Empresas",
          titulo_unidade : "Empresa",
          listar : "listar_empresas",
          selected : "selected_empresas",
          pode_editar : false,
          pode_incluir : false,
          pode_excluir : false,
          tem_sublista : true,
      };


      MANUTENCAO : any = {
          retorno : "FORNECEDORES",
          database : "MANUTENCAO",
          database_raiz : "ADMIN",
          titulo_lista : "Manutenção",
          titulo_unidade : "Manutenção",
          singular : "manutenção",
          plural : "manutenções",
          key : true,
          celular : true,
          cep : true,
          cidade : true,
          bairro : true,
          descricao : true,
          email : true,
          endereco : true,
          especialidades : true,
          estado : true,
          facebook : true,
          instagram : true,
          linkedin : true,
          img_url : true,
          nome : true,
          obs: true,
          pode_incluir : true,
          pode_excluir : true,
          pode_editar : true,
          produtos : true,
          quando : true,
          quando_update : true,
          site : true,
          telefone : true,
          whatsapp : true,
          checaratividade : true,
      };

      IMPRESSOS : any = {
          retorno : '',
          database : "IMPRESSOS",
          titulo_lista : "Impressos",
          titulo_unidade : "Impresso",
          listar : "listar_impressos",
          selected : "selected_impressos",
          pode_incluir : false,
          pode_excluir : false,
          pode_editar : false,
          tem_sublista : true,
      };

      FICHAS : any = {
          retorno : "IMPRESSOS",
          database : "FICHAS",
          titulo_lista : "Fichas",
          titulo_unidade : "Ficha",
          listar : "listar_fichas",
          selected : "selected_fichas",
          pode_editar : false,
          pode_incluir : false,
          pode_excluir : false,
          tem_sublista : true,
      };

      CARTOES : any = {
          retorno : "IMPRESSOS",
          database : "CARTOES",
          titulo_lista : "Cartões",
          titulo_unidade : "Cartão",
          listar : "listar_cartoes",
          selected : "selected_cartoes",
          pode_editar : false,
          pode_incluir : false,
          pode_excluir : false,
          tem_sublista : true,
      };

      ORIENTACOES : any = {
          retorno : "IMPRESSOS",
          database : "ORIENTACOES",
          titulo_lista : "Orientações",
          titulo_unidade : "Orientação",
          singular : "orientação",
          plural : "orientações",
          pode_editar_admin : false,
          pode_incluir_admin : false,
          tem_sublista : false,
          key : true,
          nome : true
      };

      RECEITUARIOS : any = {
          retorno : "IMPRESSOS",
          database : "RECEITUARIOS",
          titulo_lista : "Receituários",
          titulo_unidade : "Receituário",
          singular : "receituário",
          plural : "receituários",
          pode_editar_admin : false,
          pode_incluir_admin : false,
          tem_sublista : false,
          key : true,
          nome : true
      };

      RECIBOS : any = {
          retorno : "IMPRESSOS",
          database : "RECIBOS",
          titulo_lista : "Recibos",
          titulo_unidade : "Recibo",
          singular : "recibo",
          plural : "recibos",
          pode_editar_admin : false,
          pode_incluir_admin : false,
          tem_sublista : false,
          key : true,
          nome : true
      };

      REQUISICOES : any = {
          retorno : "IMPRESSOS",
          database : "REQUISICOES",
          titulo_lista : "Requisições",
          titulo_unidade : "Requisição",
          singular : "requisição",
          plural : "requisições",
          pode_editar_admin : false,
          pode_incluir_admin : false,
          tem_sublista : false,
          key : true,
          nome : true
      };

      ATESTADOS : any = {
          retorno : "IMPRESSOS",
          database : "ATESTADOS",
          titulo_lista : "Atestados",
          titulo_unidade : "Atestado",
          singular : "atestado",
          plural : "atestados",
          pode_editar_admin : false,
          pode_incluir_admin : false,
          key : true,
          tem_sublista : false,
          nome : true,
      };

      MALADIRETA : any = {
          retorno : '',
          database : "MALADIRETA",
          titulo_lista : "Mala Direta",
          titulo_unidade : "Mala Direta",
          singular : "mala direta",
          plural : "malas diretas",
          pode_editar_admin : false,
          pode_incluir_admin : false,
          key : true,
          nome : true,
          texto : true,
          tem_sublista : true
      };

      MENSAGENS : any = {
          retorno : "IMPRESSOS",
          database : "MENSAGENS",
          titulo_lista : "Mensagens",
          titulo_unidade : "Mensagem",
          singular : "mensagem",
          plural : "mensagens",
          key : true,
          criado_em : true,
          modificado_em : true,
          descricao : true,
          tem_sublista : false,
          email : true,
          nome : true,
          obs: true,
          quando : true,
          quando_update : true,
          texto : true,
          tipo : true,
          topico : true,
      };


      STATUS : any = {
          database : "STATUS",
      }



}
